"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

import { ambulatoryDispensingScenario } from "./scenario-data";
import type { DispensingChecklist, PrescriptionReview, SimulationEvent } from "./types";

type Focus = "patient" | "document" | "computer" | "prescriptions" | "tray" | "tens" | "instructions" | "handoff" | null;
type Field = "medication" | "concentration" | "form" | "quantity" | "directions";

const STORAGE_KEY = "farmaverse:operational-case-001";
const fields: Field[] = ["medication", "concentration", "form", "quantity", "directions"];
const fieldLabels: Record<Field, string> = { medication: "Medicamento", concentration: "Concentración", form: "Forma farmacéutica", quantity: "Cantidad", directions: "Indicación" };

function blankReview(): PrescriptionReview {
  return Object.fromEntries(ambulatoryDispensingScenario.prescriptions.map((prescription) => [
    prescription.id,
    { opened: false, reviewedFields: { medication: false, concentration: false, form: false, quantity: false, directions: false } },
  ]));
}

function blankChecklist(): DispensingChecklist {
  return { identificationRequested: false, patientVerifiedInSystem: false, allPrescriptionsReviewed: false, prescriptionsValidated: false, medicationPreparationChecked: false, finalPatientIdentityVerified: false, instructionsDelivered: false };
}

function Icon({ name }: { name: string }) {
  const paths: Record<string, React.ReactNode> = {
    patient: <><circle cx="12" cy="7" r="3" /><path d="M5 21c.6-4.3 3-6.5 7-6.5s6.4 2.2 7 6.5" /></>,
    card: <><rect x="3" y="5" width="18" height="14" rx="2" /><circle cx="8" cy="12" r="1.8" /><path d="M12 10h5M12 14h5M6 16h4" /></>,
    computer: <><rect x="3" y="4" width="18" height="12" rx="2" /><path d="M8 21h8M12 16v5" /></>,
    prescription: <><path d="M7 3h7l4 4v14H7z" /><path d="M14 3v5h5M10 12h5M10 16h5" /></>,
    tray: <><path d="M4 9h16l-2 10H6z" /><path d="M7 9 9 5h6l2 4M8 14h8" /></>,
    tens: <><circle cx="12" cy="7" r="3" /><path d="M6 21v-3a6 6 0 0 1 12 0v3M4 12h16" /></>,
    handoff: <><path d="M3 15h6l2 2h4l2-2h4" /><path d="M5 15V9h5l2 3 2-3h5v6M8 20h8" /></>,
    shield: <path d="M12 3 20 6v5c0 5-3.5 8.2-8 10-4.5-1.8-8-5-8-10V6z" />,
  };
  return <svg aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24">{paths[name]}</svg>;
}

export function PharmacySimulation() {
  const scenario = ambulatoryDispensingScenario;
  const [focus, setFocus] = useState<Focus>(null);
  const [checklist, setChecklist] = useState(blankChecklist);
  const [reviews, setReviews] = useState(blankReview);
  const [events, setEvents] = useState<SimulationEvent[]>([]);
  const [documentVisible, setDocumentVisible] = useState(false);
  const [systemOpen, setSystemOpen] = useState(false);
  const [trayCorrected, setTrayCorrected] = useState(false);
  const [incorrectConcentrationDetected, setIncorrectConcentrationDetected] = useState(false);
  const [openedPrepared, setOpenedPrepared] = useState<string[]>([]);
  const [instructionChoice, setInstructionChoice] = useState<string | null>(null);
  const [finalBarrier, setFinalBarrier] = useState(false);
  const [complete, setComplete] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const [hasRestoredProgress, setHasRestoredProgress] = useState(false);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const saved = window.localStorage.getItem(STORAGE_KEY);
      if (!saved) { setHasRestoredProgress(true); return; }
      try {
        const state = JSON.parse(saved) as Partial<{ checklist: DispensingChecklist; reviews: PrescriptionReview; documentVisible: boolean; systemOpen: boolean; trayCorrected: boolean; incorrectConcentrationDetected: boolean; openedPrepared: string[]; instructionChoice: string | null; events: SimulationEvent[] }>;
        if (state.checklist) setChecklist(state.checklist);
        if (state.reviews) setReviews(state.reviews);
        setDocumentVisible(Boolean(state.documentVisible)); setSystemOpen(Boolean(state.systemOpen)); setTrayCorrected(Boolean(state.trayCorrected)); setIncorrectConcentrationDetected(Boolean(state.incorrectConcentrationDetected)); setOpenedPrepared(state.openedPrepared ?? []); setInstructionChoice(state.instructionChoice ?? null); setEvents(state.events ?? []);
      } catch { window.localStorage.removeItem(STORAGE_KEY); }
      setHasRestoredProgress(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (!hasRestoredProgress) return;
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ checklist, reviews, documentVisible, systemOpen, trayCorrected, incorrectConcentrationDetected, openedPrepared, instructionChoice, events }));
  }, [checklist, reviews, documentVisible, systemOpen, trayCorrected, incorrectConcentrationDetected, openedPrepared, instructionChoice, events, hasRestoredProgress]);

  const reviewedAll = useMemo(() => scenario.prescriptions.every((p) => fields.every((field) => reviews[p.id].reviewedFields[field])), [reviews, scenario.prescriptions]);
  const openedAll = useMemo(() => scenario.prescriptions.every((p) => reviews[p.id].opened), [reviews, scenario.prescriptions]);
  const checklistForClose = { ...checklist, allPrescriptionsReviewed: reviewedAll, prescriptionsValidated: openedAll && scenario.prescriptions.every((p) => p.valid) };
  const prepared = scenario.preparedMedications.map((item) => item.id === "prepared-losartan" && trayCorrected ? { ...item, concentration: "50 mg" } : item);
  const criticalErrorRemains = !trayCorrected;

  function log(action: string) { setEvents((current) => [...current, { action, at: new Date().toISOString() }]); }
  function closeFocus() { setFocus(null); }
  function requestDocument() { setChecklist((current) => ({ ...current, identificationRequested: true })); setDocumentVisible(true); log("Solicitó documento de identidad"); }
  function searchPatient() { setChecklist((current) => ({ ...current, patientVerifiedInSystem: true })); setSystemOpen(true); log("Buscó paciente e ingresó identificador en sistema"); }
  function inspectPrescription(id: string, field?: Field) { setReviews((current) => ({ ...current, [id]: { opened: true, reviewedFields: { ...current[id].reviewedFields, ...(field ? { [field]: true } : {}) } } })); if (field) log(`Revisó ${fieldLabels[field].toLowerCase()} de ${id}`); else log(`Abrió ${id}`); }
  function inspectPrepared(id: string) { setOpenedPrepared((items) => items.includes(id) ? items : [...items, id]); log(`Inspeccionó ${id}`); }
  function confirmTray() { setChecklist((current) => ({ ...current, medicationPreparationChecked: true })); log("Confirmó preparación revisada"); closeFocus(); }
  function correctTray() { setTrayCorrected(true); setIncorrectConcentrationDetected(true); setChecklist((current) => ({ ...current, medicationPreparationChecked: false })); log("Solicitó corrección de preparación a TENS 2"); }
  function chooseInstruction(value: string) { setInstructionChoice(value); setChecklist((current) => ({ ...current, instructionsDelivered: value === "1 comprimido cada 12 horas" })); log("Entregó indicación al paciente"); }
  function verifyFinalIdentity() { setChecklist((current) => ({ ...current, finalPatientIdentityVerified: true })); log("Realizó confirmación de identidad antes del despacho"); }
  function attemptHandoff() { log("Intentó entregar medicamentos"); if (criticalErrorRemains) { setFinalBarrier(true); return; } setComplete(true); closeFocus(); }
  function restart() { window.localStorage.removeItem(STORAGE_KEY); setFocus(null); setChecklist(blankChecklist()); setReviews(blankReview()); setEvents([]); setDocumentVisible(false); setSystemOpen(false); setTrayCorrected(false); setIncorrectConcentrationDetected(false); setOpenedPrepared([]); setInstructionChoice(null); setFinalBarrier(false); setComplete(false); }

  return <section className="overflow-hidden rounded-[22px] border border-slate-300 bg-[#d9e4e1] shadow-[0_28px_70px_rgb(15_23_42/.2)]">
    <header className="bg-gradient-to-r from-[#031225] via-[#09253e] to-[#031225] px-5 py-3 text-white"><p className="text-base font-extrabold">SIMULACIÓN: DISPENSACIÓN SEGURA PARA <span className="text-teal-300">TENS</span></p></header>
    <nav aria-label="Progreso operativo" className="flex items-center gap-2 overflow-x-auto bg-white/95 px-5 py-3 text-sm font-bold text-slate-600">{["Identificar", "Verificar sistema", "Revisar recetas", "Doble chequeo", "Despachar"].map((stage, index) => <div className={`flex shrink-0 items-center gap-2 ${index === 2 ? "rounded-xl bg-slate-100 px-3 py-2 text-slate-900" : ""}`} key={stage}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${index < 2 ? "bg-teal-600 text-white" : index === 2 ? "bg-blue-700 text-white" : "border border-slate-300 bg-white text-slate-500"}`}>{index < 2 ? "✓" : index + 1}</span>{stage}{index < 4 ? <span className="ml-3 text-slate-400">→</span> : null}</div>)}</nav>
    <div className="grid gap-3 p-3 xl:grid-cols-[310px_minmax(0,1fr)_310px]">
      <aside className="rounded-2xl border border-slate-300 bg-[#edf3f1] p-3 shadow-lg"><div className="flex items-center justify-between rounded-lg bg-[#073a5f] px-3 py-2 text-sm font-extrabold text-white"><span>SISTEMA DE GESTIÓN DE FARMACIA</span><Icon name="computer" /></div><div className="mt-3 rounded-xl border border-slate-300 bg-white p-3"><div className="flex gap-3"><div className="flex h-20 w-16 items-center justify-center rounded-lg bg-slate-200 text-slate-500"><Icon name="patient" /></div><div className="text-xs leading-5"><b className="text-sm">Ficha del paciente</b><p className="mt-1">RUT: {documentVisible ? scenario.patient.rut : "—"}</p><p>Nombre: {systemOpen ? scenario.patient.fullName : "—"}</p><p>Alertas: No conocidas</p></div></div></div><div className="mt-3 flex items-center justify-between text-sm font-bold"><span>Recetas del día</span><span>{scenario.prescriptions.filter((prescription) => reviews[prescription.id].opened).length}/3</span></div><div className="mt-2 space-y-2">{scenario.prescriptions.map((prescription, index) => <button className="flex w-full items-center gap-3 rounded-lg border border-slate-200 bg-white p-3 text-left hover:border-teal-400" key={prescription.id} onClick={() => setFocus("prescriptions")} type="button"><span className={`rounded-md p-2 ${reviews[prescription.id].opened ? "bg-teal-100 text-teal-700" : "bg-blue-100 text-blue-700"}`}><Icon name="prescription" /></span><span className="min-w-0"><b className="block text-sm">Receta {index + 1} {reviews[prescription.id].opened ? "revisada" : "pendiente"}</b><span className="text-xs text-slate-600">{prescription.medication.name} {prescription.medication.concentration}</span></span></button>)}</div><button className="mt-3 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-left text-xs font-bold text-slate-600" onClick={() => setFocus("computer")} type="button">Abrir ficha e historial</button></aside>
      <main className="relative min-h-[490px] overflow-hidden rounded-2xl border border-slate-300 bg-slate-200 shadow-xl"><Image alt="Farmacia ficticia para entrenamiento" className="object-cover" fill priority sizes="(max-width: 1280px) 100vw, 55vw" src="/scenes/pharmacy-training-room-v3.png" /><div className="absolute inset-0 bg-gradient-to-t from-[#071c2a99] via-transparent to-transparent" /><button className="absolute bottom-0 left-1/2 z-10 w-[48%] min-w-52 max-w-96 -translate-x-1/2 focus-visible:outline-4 focus-visible:outline-teal-300" onClick={() => setFocus("patient")} type="button"><Image alt="Paciente virtual Luis Herrera" className="h-auto w-full drop-shadow-[0_18px_14px_rgb(0_0_0/.3)]" draggable={false} height={1536} sizes="(max-width: 700px) 62vw, 24rem" src="/scenes/patient-a01-3d-render-v3.png" width={1024} /></button><div className="absolute right-4 top-5 z-20 max-w-48 rounded-xl border border-teal-300 bg-[#063a47]/90 p-3 text-white shadow-lg"><b className="text-sm">Documento de identidad</b><p className="mt-1 text-xs leading-5">Haz clic para solicitar y verificar.</p><button className="mt-2 rounded-lg bg-teal-400 px-3 py-2 text-xs font-bold text-slate-950" onClick={() => setFocus("patient")} type="button">Solicitar documento</button></div><button aria-label="Revisar bandeja preparada" className="absolute bottom-10 right-5 z-20 rounded-xl border border-teal-200 bg-[#063a47]/95 p-3 text-left text-white shadow-lg" onClick={() => setFocus("tray")} type="button"><span className="flex items-center gap-2 text-sm font-bold"><Icon name="tray" /> Bandeja preparada</span><span className="mt-1 block text-xs text-teal-100">Haz clic para revisar contenido</span></button><button aria-label="Abrir sistema" className="absolute bottom-10 left-5 z-20 rounded-xl border border-white/60 bg-white/90 p-3 text-left text-slate-900 shadow-lg" onClick={() => setFocus("computer")} type="button"><span className="flex items-center gap-2 text-sm font-bold"><Icon name="computer" /> Sistema</span><span className="mt-1 block text-xs text-slate-600">Ficha y prescripciones</span></button></main>
      <aside className="space-y-3"><section className="rounded-2xl border border-slate-300 bg-[#081824] p-4 text-white shadow-lg"><p className="text-[10px] font-extrabold tracking-wider text-slate-300">VISTA PREVIA: CONSECUENCIA FINAL</p><div className="mt-3 rounded-xl border border-slate-600 bg-black/25 p-4 text-center"><div className="text-2xl font-black text-[#ff684f]">DETENTE</div><p className="mt-1 text-xs font-bold text-[#ff684f]">ERROR DE MEDICACIÓN INTERCEPTADO</p><p className="mt-3 text-xs leading-5 text-slate-200">Esta alerta se muestra solo si una discrepancia llega al momento de entrega.</p></div></section><section className="rounded-2xl border border-slate-300 bg-white shadow-lg"><div className="flex items-center gap-2 rounded-t-2xl bg-[#073a47] px-4 py-3 text-sm font-extrabold text-white">ACCIONES Y HERRAMIENTAS</div><div className="divide-y divide-slate-200">{[["Solicitar documento", "card", () => setFocus("patient")], ["Abrir ficha", "computer", () => setFocus("computer")], ["Revisar bandeja", "tray", () => setFocus("tray")], ["Solicitar corrección", "tens", () => setFocus("tray")], ["Dar indicaciones", "patient", () => setFocus("instructions")]].map(([label, icon, action]) => <button className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-50" key={label as string} onClick={action as () => void} type="button"><span className="rounded-lg bg-teal-50 p-2 text-teal-700"><Icon name={icon as string} /></span><span><b className="block text-sm">{label as string}</b><span className="block text-xs text-slate-500">Interactuar en la estación</span></span></button>)}</div></section>{showDebug ? <pre className="max-h-40 overflow-auto rounded-xl bg-slate-950 p-3 text-[10px] leading-5 text-teal-200">{JSON.stringify({ checklist: checklistForClose, trayCorrected, incorrectConcentrationDetected, events }, null, 2)}</pre> : null}<button className="text-xs font-bold text-slate-600 underline" onClick={() => setShowDebug((value) => !value)} type="button">Depuración</button></aside>
      <section className="rounded-2xl border border-slate-300 bg-[#f7f5ef] p-4 shadow-lg xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-300 pb-2"><b className="text-sm text-[#073a47]">INSPECCIÓN DEL PRODUCTO: COMPARA ANTES DE CONTINUAR</b><button className="text-xs font-bold text-teal-700 underline" onClick={() => setFocus("tray")} type="button">Abrir bandeja</button></div><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_auto_1fr]"><ProductInspection heading="PRESCRIPCIÓN (RECETA 1)" concentration="50 mg" tone="teal" /><div className="hidden items-center justify-center text-3xl text-slate-500 sm:flex">↔</div><ProductInspection heading="PRODUCTO PREPARADO (BANDEJA)" concentration={prepared[0].concentration} tone="blue" /></div><p className="mt-4 text-center text-xs font-semibold text-slate-600">Revisa: paciente correcto, medicamento correcto, concentración correcta, forma farmacéutica y cantidad.</p></section>
      <section className="flex flex-col justify-between rounded-2xl border border-slate-300 bg-white p-4 shadow-lg"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-50 p-3 text-teal-700"><Icon name="shield" /></span><p className="text-xs leading-5"><b className="block text-sm">Barrera de seguridad activa</b>Realiza el doble chequeo antes de entregar.</p></div><button className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-sm font-extrabold text-white hover:bg-slate-800" onClick={() => setFocus("handoff")} type="button">ENTREGAR MEDICAMENTOS</button></section>
    </div>
    {focus ? <InteractionDialog focus={focus} scenario={scenario} documentVisible={documentVisible} systemOpen={systemOpen} reviews={reviews} prepared={prepared} openedPrepared={openedPrepared} trayCorrected={trayCorrected} instructionChoice={instructionChoice} onClose={closeFocus} onRequestDocument={requestDocument} onSearchPatient={searchPatient} onInspectPrescription={inspectPrescription} onInspectPrepared={inspectPrepared} onConfirmTray={confirmTray} onCorrectTray={correctTray} onChooseInstruction={chooseInstruction} onVerifyFinalIdentity={verifyFinalIdentity} onAttemptHandoff={attemptHandoff} /> : null}
    {finalBarrier ? <FinalSafetyBarrier onContinue={() => { setFinalBarrier(false); setFocus("tray"); }} /> : null}
    {complete ? <SimulationFeedback checklist={checklistForClose} onRestart={restart} /> : null}
  </section>;
}

function ProductInspection({ heading, concentration, tone }: { heading: string; concentration: string; tone: "teal" | "blue" }) {
  const color = tone === "teal" ? "bg-teal-700" : "bg-blue-700";
  return <div><p className="text-xs font-extrabold text-[#073a47]">{heading}</p><div className="mt-3 flex items-center gap-4"><div className={`flex h-28 w-20 shrink-0 flex-col justify-between rounded-md border border-slate-300 bg-white p-2 shadow-sm`}><span className="text-[9px] font-bold text-slate-500">LOSARTÁN</span><span className={`-mx-2 px-2 py-2 text-center text-sm font-black text-white ${color}`}>{concentration}</span><span className="text-[8px] font-bold text-slate-500">30 comprimidos</span></div><div className="text-sm leading-6"><b className="text-lg">Losartán {concentration}</b><p>30 comprimidos</p><p className="mt-2 text-xs text-slate-600">Forma: comprimido<br />Vía: oral<br />Cantidad: 30</p></div></div></div>;
}

function InteractionDialog({ focus, scenario, documentVisible, systemOpen, reviews, prepared, openedPrepared, trayCorrected, instructionChoice, onClose, onRequestDocument, onSearchPatient, onInspectPrescription, onInspectPrepared, onConfirmTray, onCorrectTray, onChooseInstruction, onVerifyFinalIdentity, onAttemptHandoff }: { focus: Exclude<Focus, null>; scenario: typeof ambulatoryDispensingScenario; documentVisible: boolean; systemOpen: boolean; reviews: PrescriptionReview; prepared: typeof ambulatoryDispensingScenario.preparedMedications; openedPrepared: string[]; trayCorrected: boolean; instructionChoice: string | null; onClose: () => void; onRequestDocument: () => void; onSearchPatient: () => void; onInspectPrescription: (id: string, field?: Field) => void; onInspectPrepared: (id: string) => void; onConfirmTray: () => void; onCorrectTray: () => void; onChooseInstruction: (value: string) => void; onVerifyFinalIdentity: () => void; onAttemptHandoff: () => void }) {
  const heading: Record<Exclude<Focus, null>, string> = { patient: "Paciente virtual", document: "Documento de identidad", computer: "Sistema de ficha", prescriptions: "Prescripciones", tray: "Bandeja de preparación", tens: "Segunda TENS", instructions: "Indicaciones al paciente", handoff: "Despacho" };
  return <div aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/55 p-3 backdrop-blur-sm sm:items-center" role="dialog"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-[24px] bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold tracking-[.15em] text-teal-700">INTERACCIÓN CONTEXTUAL</p><h3 className="mt-1 text-2xl font-bold text-slate-950">{heading[focus]}</h3></div><button aria-label="Cerrar" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" onClick={onClose} type="button">Cerrar</button></div><div className="mt-5">{focus === "patient" ? <div><p className="text-lg leading-8 text-slate-700">“Buenas tardes, vengo a retirar mis medicamentos.”</p><div className="mt-5 flex flex-wrap gap-3"><Action label="Solicitar documento" onClick={onRequestDocument} /><Action label="Preguntar por el retiro" onClick={onClose} secondary /><Action label="Solicitar esperar un momento" onClick={onClose} secondary /></div></div> : null}
  {focus === "document" ? <div>{documentVisible ? <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="text-xs font-bold tracking-wider text-slate-500">CARNET · DATOS FICTICIOS</p><p className="mt-4 text-xl font-bold">{scenario.patient.fullName}</p><p className="mt-1 text-slate-600">RUT {scenario.patient.rut}</p></div> : <p className="leading-7 text-slate-600">El paciente puede presentar su documento durante la atención. Puedes solicitarlo directamente al paciente.</p>}</div> : null}
  {focus === "computer" ? <div><p className="text-slate-600">Terminal de consulta del paciente.</p><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><label className="text-xs font-bold text-slate-600">RUT / identificador</label><div className="mt-2 flex gap-2"><input className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm" defaultValue={documentVisible ? scenario.patient.rut : ""} placeholder="Ingresa identificador" readOnly /><Action label={systemOpen ? "Ficha abierta" : "Buscar paciente"} onClick={onSearchPatient} /></div></div>{systemOpen ? <div className="mt-4 rounded-xl border border-teal-200 bg-teal-50 p-4"><b>{scenario.patient.fullName}</b><p className="mt-1 text-sm text-teal-900">Ficha ficticia encontrada. Abre las prescripciones desde el panel correspondiente.</p></div> : null}</div> : null}
  {focus === "prescriptions" ? <div className="space-y-3">{scenario.prescriptions.map((prescription) => <PrescriptionCard key={prescription.id} prescription={prescription} review={reviews[prescription.id]} onInspect={onInspectPrescription} />)}</div> : null}
  {focus === "tray" ? <div><p className="text-slate-600">La TENS 2 dejó la preparación sobre el mesón. Consulta cada caja y contrástala con la ficha si lo consideras necesario.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{prepared.map((medication) => <button className={`rounded-2xl border p-4 text-left transition hover:border-teal-400 ${openedPrepared.includes(medication.id) ? "border-teal-300 bg-teal-50" : "border-slate-200 bg-white"}`} key={medication.id} onClick={() => onInspectPrepared(medication.id)} type="button"><span className="text-[10px] font-extrabold tracking-wider text-teal-700">CAJA</span><b className="mt-2 block text-lg">{medication.name}</b><p className="mt-1 text-sm text-slate-600">{openedPrepared.includes(medication.id) ? `${medication.concentration} · ${medication.form} · ${medication.quantity} unidades` : "Abrir para revisar"}</p></button>)}</div><div className="mt-5 flex flex-wrap gap-3"><Action label="Preparación revisada" onClick={onConfirmTray} /><Action label={trayCorrected ? "Corrección solicitada" : "Solicitar corrección a TENS 2"} onClick={onCorrectTray} secondary /></div></div> : null}
  {focus === "tens" ? <div><p className="leading-7 text-slate-600">La segunda TENS realizó la preparación y la dejó disponible en bandeja. Su preparación requiere una revisión independiente antes del despacho.</p><Action label="Revisar bandeja" onClick={() => { onClose(); }} /></div> : null}
  {focus === "instructions" ? <div><p className="text-slate-600">El paciente pregunta cómo debe tomar Losartán. Selecciona la indicación que entregarás.</p><div className="mt-4 grid gap-3">{["1 comprimido cada 12 horas", "1 comprimido cada 24 horas", "2 comprimidos cada 12 horas"].map((option) => <button className={`rounded-xl border p-4 text-left text-sm font-semibold ${instructionChoice === option ? "border-teal-500 bg-teal-50 text-teal-950" : "border-slate-200 hover:border-teal-300"}`} key={option} onClick={() => onChooseInstruction(option)} type="button">{option}</button>)}</div></div> : null}
  {focus === "handoff" ? <div><p className="leading-7 text-slate-600">Antes de entregar, aún puedes confirmar la identidad del paciente o revisar nuevamente la preparación.</p><div className="mt-5 flex flex-wrap gap-3"><Action label="Confirmar nombre y RUT" onClick={onVerifyFinalIdentity} secondary /><Action label="ENTREGAR MEDICAMENTOS" onClick={onAttemptHandoff} /></div></div> : null}</div></div></div>;
}

function PrescriptionCard({ prescription, review, onInspect }: { prescription: typeof ambulatoryDispensingScenario.prescriptions[number]; review: PrescriptionReview[string]; onInspect: (id: string, field?: Field) => void }) {
  return <article className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">PRESCRIPCIÓN {prescription.id.slice(-2)}</p><b>{prescription.medication.name}</b></div><Action label={review.opened ? "Registro abierto" : "Abrir registro"} onClick={() => onInspect(prescription.id)} secondary /></div>{review.opened ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{fields.map((field) => <button className={`rounded-lg border px-3 py-2 text-left text-sm ${review.reviewedFields[field] ? "border-teal-300 bg-teal-50" : "border-slate-200 bg-white hover:border-teal-300"}`} key={field} onClick={() => onInspect(prescription.id, field)} type="button"><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">{fieldLabels[field]}</span><span className="font-semibold">{field === "medication" ? prescription.medication.name : field === "concentration" ? prescription.medication.concentration : field === "form" ? prescription.medication.form : field === "quantity" ? prescription.medication.quantity : prescription.medication.directions}</span></button>)}</div> : null}</article>;
}

function Action({ label, onClick, secondary = false }: { label: string; onClick: () => void; secondary?: boolean }) { return <button className={`rounded-xl px-4 py-3 text-sm font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 ${secondary ? "border border-slate-300 bg-white text-slate-800 hover:bg-slate-50" : "bg-teal-700 text-white hover:bg-teal-800"}`} onClick={onClick} type="button">{label}</button>; }

function FinalSafetyBarrier({ onContinue }: { onContinue: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-[60] flex items-center justify-center bg-[#050b19]/80 p-4 backdrop-blur-md" role="alertdialog"><div className="w-full max-w-2xl rounded-[28px] border border-amber-400/50 bg-white p-7 shadow-2xl sm:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><Icon name="shield" /></div><p className="mt-6 text-sm font-extrabold tracking-[.16em] text-amber-700">DETENTE</p><h2 className="mt-2 text-3xl font-bold text-slate-950">Error de medicación interceptado</h2><p className="mt-3 font-bold text-rose-700">NO ENTREGAR</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-bold tracking-wide text-slate-500">PRESCRIPCIÓN</p><p className="mt-2 font-semibold">Losartán 50 mg<br />Comprimidos · cantidad 30</p></div><div className="rounded-2xl border border-rose-200 bg-rose-50 p-4"><p className="text-xs font-bold tracking-wide text-rose-700">PREPARACIÓN</p><p className="mt-2 font-semibold text-rose-950">Losartán 100 mg<br />Comprimidos · cantidad 30</p></div></div><p className="mt-6 leading-7 text-slate-700">La concentración incorrecta no fue detectada durante el doble chequeo. La simulación interceptó el error antes de que el medicamento alcanzara al paciente.</p><Action label="Volver a la preparación" onClick={onContinue} /></div></div>; }

function SimulationFeedback({ checklist, onRestart }: { checklist: DispensingChecklist; onRestart: () => void }) { const criteria = [{ label: "Identificación", value: checklist.identificationRequested }, { label: "Verificación en sistema", value: checklist.patientVerifiedInSystem }, { label: "Prescripciones", value: checklist.allPrescriptionsReviewed }, { label: "Recetas emitidas", value: checklist.prescriptionsValidated }, { label: "Preparación", value: checklist.medicationPreparationChecked }, { label: "Identidad final", value: checklist.finalPatientIdentityVerified }, { label: "Indicaciones", value: checklist.instructionsDelivered }]; return <div aria-modal="true" className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm" role="dialog"><div className="w-full max-w-2xl rounded-[28px] bg-white p-7 shadow-2xl sm:p-10"><p className="text-xs font-extrabold tracking-[.15em] text-teal-700">CIERRE DEL ESCENARIO</p><h2 className="mt-2 text-3xl font-bold">Proceso finalizado</h2><div className="mt-6 rounded-2xl border border-teal-200 bg-teal-50 p-5"><p className="font-bold text-teal-950">NO OLVIDAR</p><p className="mt-2 leading-7 text-teal-900">Antes del despacho verifica medicamento, concentración, forma farmacéutica y cantidad.</p></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{criteria.map((criterion) => <div className="rounded-xl border border-slate-200 p-3 text-sm" key={criterion.label}><b>{criterion.label}</b><span className={`ml-2 text-xs font-bold ${criterion.value ? "text-teal-700" : "text-amber-700"}`}>{criterion.value ? "Cumplido" : "En refuerzo"}</span></div>)}</div><p className="mt-6 text-sm leading-6 text-slate-600">Para el siguiente caso, se puede reforzar la misma competencia con una concentración distinta, por ejemplo Amlodipino 5 mg versus 10 mg.</p><Action label="Reiniciar escenario" onClick={onRestart} /></div></div>; }
